### PR TITLE
Create athelete_sort.cpp

### PR DESCRIPTION
**Pull request by syamala27**
Hello sir,

Good Afternoon !!

I have added the athlete sort problem. Please kindly review it and if any changes are required pls guide me @De-Coder-01 sir.

### CODE REVIEW

**Comment by De-Coder-01** [comment]
Fix the typo in file name @syamala27

**Comment by syamala27** [comment]
@De-Coder-01 Sir, the filename is  `athelet_sort.cpp`, what changes I have to make in the file name please guide me.

**Comment by De-Coder-01** [comment]
It should be `athlete_sort.cpp` instead of `athelet_sort.cpp`

**Comment by syamala27** [comment]
sir, I have renamed the filename. Thank you for guiding.

**Pull request merged**
